language: cpp
compiler:
  - gcc
  - clang

before_install: sudo apt-get update

install: sudo apt-get install libpwquality-dev libblkid-dev libqt4-dev gcc g++ libcryptsetup-dev cmake libtcplay-dev libgcrypt11-dev libsecret-1-dev pkg-config libdevmapper-dev uuid-dev libudev-dev chrpath bzip2 debhelper

script: cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=lib/$(DEB_HOST_MULTIARCH) -DCMAKE_BUILD_TYPE=release . && make
